; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
; IMPORTANT: enables OPI PSRAM + QIO flash in Arduino core
board_build.arduino.memory_type = qio_opi
board_build.psram = enabled
board_build.memory_type = qio_opi

board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_deps =
  ;ESP32Async/ESPAsyncWebServer @ 3.6.0
  ;ESP32Async/AsyncTCP @ ^3.3.2
	gilmaimon/ArduinoWebsockets
	h2zero/NimBLE-Arduino
 	esphome/ESP32-audioI2S@^2.0.7
	adafruit/Adafruit NeoPixel@^1.15.2
	bitbank2/PNGdec ; or simply bitbank2/PNGdec
    bblanchon/ArduinoJson @ ^6.21.3

build_flags = 
	-Wall
	;-Wextra
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D CORE_DEBUG_LEVEL=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1
	-D CONFIG_SOC_SDMMC_HOST_SUPPORTED=y
	-D CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192

;[platformio]
;boards_dir = ./boards
